version: "3.9"
services:
  mongodb:      
    build: ./mongodb
    image: mongodb
    container_name: mongodb  
    volumes:
      - ~/volumes/mongodata/mongobingo/data:/data/db
      - ~/volumes/mongodata/mongobingo/logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=7777
    command: mongod
    networks:
      mnet:
        aliases:
          - mongodb
          
  sendemail:
    image: sendemail     
    build: ./sendemail
    container_name: sendemail 
    links:
      - mongodb
    ports:
      - 2070:2070 
    depends_on:     
      - mongodb  
    networks:
     - mnet
  
networks:
  mnet:
    driver: bridge
